# Generated by Django 4.1.1 on 2022-11-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
