# Generated by Django 4.1.1 on 2022-11-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_remove_customer_store_custo_first_n_a7e990_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='store_customers',
        ),
    ]
