# Generated by Django 4.1.1 on 2022-11-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_collection_featured_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='cutomer',
            new_name='customer',
        ),
    ]
