# Generated by Django 4.1.1 on 2022-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_product_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='promotions',
            field=models.ManyToManyField(related_name='promoted_product', to='Store.promotion'),
        ),
    ]
