# Generated by Django 4.1.1 on 2022-11-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0018_alter_product_slug'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customer',
            new_name='store_custo_first_n_8f83e0_idx',
            old_name='store_custo_first_n_a7e990_idx',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store_customer',
        ),
    ]
